export const API_END_POINT = {
  auth: {
    login: 'login',
  },
  user: {
    getProfile: 'get-profile',
    updateProfile: 'update-profile',
    updateProfilePhoto: 'change-profile-picture',
  },
  customer: {
    list: 'customer/list',
    add: 'customer/add',
    get: 'customer/show',
    update: 'customer/update',
    delete: 'customer/delete',
  },
  customer_address: {
    add: 'customer/address/add',
    update: 'customer/address/update',
    list: 'customer/address/list',
    get: 'customer/address/show',
    delete: 'customer/address/delete',
  },
  type_margin: {
    list: 'order-type-margin/list',
    add: 'order-type-margin/add',
    get: 'order-type-margin/show',
    update: 'order-type-margin/update',
    delete: 'order-type-margin/delete',
  },
  area: {
    list: 'area/list',
    add: 'area/add',
    get: 'area/show',
    update: 'area/update',
  },
  paymentType: {
    list: 'payment-term/list',
    add: 'payment-term/add',
    get: 'payment-term/show',
    update: 'payment-term/update',
    delete: 'payment-term/delete',
  },
  footer: {
    list: 'footer/list',
    add: 'footer/add',
    get: 'footer/show',
    update: 'footer/update',
  },
  header: {
    list: 'header/list',
    add: 'header/add',
    get: 'header/show',
    update: 'header/update',
  },
  product: {
    category: 'product/get-category',
    productList: 'product/get-product-list',
    productDropdown: 'product/get-products',
    productType: 'product/type',
    get: 'product',
    add: 'product/add',
    edit: 'product/update',
    sliddingTypes: 'product/slidding-type',
    hingesType: 'product/hinges-type',
    allDropdowns: 'product/dropdowns',
  },
  costHead: {
    base: 'costhead',
    costHeadTypes: 'costhead-type',
    costHeadData: 'costhead/data',
    costHeadList: 'costhead/list',
    costHeadAdd: 'costhead/add',
    costHeadUpdate: 'costhead/update',
    get: 'costhead/show',
    unit: 'costhead/cal-type',
  },
  quatation: {
    list: 'quatation/list',
    add: 'quatation/add',
    edit: 'quatation/update',
    show: 'quatation/show',
    delete: 'quatation/delete',
    deleteProduct: 'quatation/product/delete',
    subQuotationDetail: 'quatation/show-product',
    casementTypes: 'product/casement-type',
    sliddingTypes: 'product/slidding-type',
    pallaTypesOpenable: 'product/palla-type-openable',
    pallaTypesSlidding: 'product/palla-type-slidding',
    pdf: 'quatation/pdf',
    manageProduct: 'quatation/manage-product',
    openningDirection: 'product/opening-direction',
  },
  profile_color: {
    list: 'profile-color/list',
    detail: 'profile-color/show/',
    add: 'profile-color/add',
    update: 'profile-color/update/',
    delete: 'profile-color/delete/',
    dropdown: 'profile-color/dropdown',
  },
  bulkPriceUpdate: {
    get: 'setting/get-price',
    post: 'setting/update-price',
  },
};
